version: "3.7"

services:
  database: 
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/data/postgres
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  
  # app:
  #   build: .
  #   container_name: rentx
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database

volumes:
  pgdata:
    driver: local